on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run fetch-data.js
        run: node fetch-data.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pass the GitHub token from secrets
